---
# tasks file for apache
- name: Update All Packages
  yum:
    name: "*"
    state: latest

- name: Install Apache
  yum:
    name: httpd
    state: installed

- name: Create The HTML File
  shell: echo "Hello From The Ansible Galaxy Challenge" > /var/www/html/index.html
  # By default, the shell used is "/bin/sh". But the Bash shell has better priviledges. Thus we are using the "/bin/bash"
  args:
    executable: /bin/bash
  notify:
    - Reload Apache

- name: Public IP
  shell:
    cmd: curl http://169.254.169.254/latest/meta-data/public-hostname
    # cmd: service httpd status
    
  register: curl
- debug: var=curl.stdout_lines

# - name: Uninstall Apache
#   yum:
#     name: httpd
#     state: removed


